# LUIS FERNANDO ARELLANO MARTINEZ 250152
# PRESUPUESTO DE UN HOSPITAL

print("Calcularemos el presupuesto anual de cada departamento del hospital")
pre= float(input("Cual fue el presupuesto Anual?: "))
gine= pre*0.40
trau= pre*0.30
pedi= pre*0.30

print(f"El presupuesto de Anual de Ginecologia fue de {gine}")
print(f"El presupuesto de Anual de Traumatologia fue de {trau}")
print(f"EL presupuesto de Anual de Pediatria fue de: {pedi}")
